/*
let age = 71
let country = "UK"
let day = "sunny"

if (age < 17) {
    console.log("yes, i can serve you.")
}
else if (age >17 && (country == "UK")){
    console.log("over 17 and from UK")
}
if (country == "UK"){
    console.log("amazing")
}

else if (day == "sunny"){
    console.log("sunny")
}
*/
/*
let Password = "Password"
if (Password.length < 8){
    console.log("Incorrect password")
}

else {
    console.log("Access granted")
}
*/
let num = 15
if (num % 5 ==0){
    console.log("Number divisible by 5")
}

else {
    console.log("Number not divisible by 3")
}
let num 27372

let time = "time"
let town of home = 
let place of work =     